spring:
  ai:
    openai:
      api-key: "sk-"
      base-url: "https://api.agicto.cn"
      chat:
        options:
          model: "gpt-4o-mini"
server:
  port: 8000
candy:
  ai:
    deepseek:
      enable: "true"
      api-key: "sk-"

